#mqtthost: 192.168.0.10
#mqtthost: 10.24.69.200
mqtthost: 10.1.5.70
mqttport: 1883
# needs / in the end
spfx: _1451.1.6/
tomdop: D/
tomcop: D0C/
tomd0op: D0/
# Does not need / in the end
loc: plugfest/2021/ncap0/
locclient: plugfest/2021/application0/
slowsample: 1
fastsample: 500
reqtopic: NCAP/1451OPE
restopic: SERVICE/1451RES
#username: iesstd        not for MQTTv5
#password: 1451Plugfest        not for MQTTv5
##alpsmodule1: 48:F0:7B:78:47:46
alpsmodule1: 48:F0:7B:78:47:4B
#alpsmodule3: 48:F0:7B:78:47:4C
#alpsmodule4: 48:F0:7B:78:47:25
#alpsmodule5: 48:F0:7B:78:47:33
#alpsmodule6: 48:F0:7B:78:47:35
#alpsmodule7: 48:F0:7B:78:47:36
#alpsmodule8: 48:F0:7B:78:47:4E
